#!/usr/bin/env python3
"""
Automated Molecular Docking Pipeline using AutoDock Vina
=========================================================
Author  : Sana Begum
Role    : Research Analyst, Era's Lucknow Medical College & Hospital
Email   : begumsana686@gmail.com
GitHub  : https://github.com/Sanabegum09

Description
-----------
This script automates high-throughput molecular docking of a ligand library
against a prepared protein receptor using AutoDock Vina. It parses docking
results, ranks compounds by binding affinity, extracts the best poses, and
exports a summary CSV for downstream ADMET analysis.

Usage
-----
    python autodock_vina_pipeline.py \
        --receptor protein_prepared.pdbqt \
        --ligands_dir ligands_pdbqt/ \
        --config docking_config.txt \
        --output results/

Requirements
------------
    - AutoDock Vina (in PATH)
    - Open Babel (obabel, in PATH)
    - Python >= 3.8
    - pandas, numpy

References
----------
    Trott O, Olson AJ. AutoDock Vina: improving the speed and accuracy of
    docking. J Comput Chem. 2010;31(2):455-61. doi:10.1002/jcc.21334
"""

import os
import sys
import glob
import subprocess
import argparse
import logging
import csv
import re
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

# ─────────────────────────────────────────────────────────────
# LOGGING SETUP
# ─────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(f"docking_pipeline_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")
    ]
)
log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────
def generate_vina_config(
    receptor_path: str,
    center_x: float, center_y: float, center_z: float,
    size_x: float = 20.0, size_y: float = 20.0, size_z: float = 20.0,
    exhaustiveness: int = 8,
    num_modes: int = 9,
    energy_range: float = 3.0,
    config_path: str = "docking_config.txt"
) -> str:
    """
    Generate an AutoDock Vina configuration file.

    Parameters
    ----------
    receptor_path : str
        Path to the prepared receptor (.pdbqt)
    center_x, center_y, center_z : float
        Grid box centre coordinates (Angstrom)
    size_x, size_y, size_z : float
        Grid box dimensions (Angstrom). Default: 20 x 20 x 20
    exhaustiveness : int
        Search exhaustiveness. Default: 8 (increase for accuracy)
    num_modes : int
        Number of binding poses to generate
    energy_range : float
        Max energy difference (kcal/mol) between best and worst mode
    config_path : str
        Output path for the config file

    Returns
    -------
    str : Path to the written config file
    """
    config_content = f"""# AutoDock Vina Configuration
# Generated by Sana Begum's docking pipeline
# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

receptor = {receptor_path}

center_x = {center_x}
center_y = {center_y}
center_z = {center_z}

size_x = {size_x}
size_y = {size_y}
size_z = {size_z}

exhaustiveness = {exhaustiveness}
num_modes = {num_modes}
energy_range = {energy_range}
"""
    with open(config_path, "w") as fh:
        fh.write(config_content)
    log.info(f"Docking config written to: {config_path}")
    return config_path


# ─────────────────────────────────────────────────────────────
# LIGAND PREPARATION
# ─────────────────────────────────────────────────────────────
def prepare_ligands_from_sdf(sdf_file: str, output_dir: str) -> list:
    """
    Convert SDF library to individual PDBQT files using Open Babel.

    Parameters
    ----------
    sdf_file : str
        Input multi-molecule SDF file
    output_dir : str
        Directory to save individual PDBQT files

    Returns
    -------
    list : Paths to generated PDBQT files
    """
    os.makedirs(output_dir, exist_ok=True)
    cmd = [
        "obabel", sdf_file,
        "-O", os.path.join(output_dir, "lig.pdbqt"),
        "-m",                     # split into individual files
        "--gen3d",                # generate 3D coordinates if absent
        "-h",                     # add hydrogens
        "--partialcharge", "gasteiger"
    ]
    log.info(f"Preparing ligands from {sdf_file}...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        log.warning(f"Open Babel warning: {result.stderr}")

    pdbqt_files = sorted(glob.glob(os.path.join(output_dir, "*.pdbqt")))
    log.info(f"Prepared {len(pdbqt_files)} ligand PDBQT files.")
    return pdbqt_files


# ─────────────────────────────────────────────────────────────
# DOCKING ENGINE
# ─────────────────────────────────────────────────────────────
def run_vina(
    config_path: str,
    ligand_path: str,
    out_path: str,
    log_path: str,
    vina_executable: str = "vina"
) -> dict:
    """
    Run a single AutoDock Vina docking calculation.

    Parameters
    ----------
    config_path : str
        Path to Vina config file
    ligand_path : str
        Path to ligand PDBQT
    out_path : str
        Path for docked output PDBQT
    log_path : str
        Path for Vina log file
    vina_executable : str
        Name/path of Vina executable

    Returns
    -------
    dict : {'ligand', 'best_affinity', 'all_affinities', 'out_pdbqt', 'success'}
    """
    cmd = [
        vina_executable,
        "--config", config_path,
        "--ligand", ligand_path,
        "--out", out_path,
        "--log", log_path
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    ligand_name = Path(ligand_path).stem

    if result.returncode != 0:
        log.warning(f"Vina failed for {ligand_name}: {result.stderr[:200]}")
        return {
            "ligand": ligand_name, "best_affinity": None,
            "all_affinities": [], "out_pdbqt": out_path, "success": False
        }

    # Parse binding affinities from log
    affinities = parse_vina_log(log_path)
    best = affinities[0] if affinities else None

    return {
        "ligand": ligand_name,
        "best_affinity": best,
        "all_affinities": affinities,
        "out_pdbqt": out_path,
        "success": True
    }


def parse_vina_log(log_path: str) -> list:
    """
    Extract binding affinities from a Vina log file.

    Returns list of floats (kcal/mol), sorted best to worst.
    """
    affinities = []
    try:
        with open(log_path) as fh:
            for line in fh:
                # Vina output: "   1       -7.4      0.000      0.000"
                m = re.match(r"\s+\d+\s+(-?\d+\.\d+)\s+", line)
                if m:
                    affinities.append(float(m.group(1)))
    except FileNotFoundError:
        pass
    return sorted(affinities)   # most negative = best


# ─────────────────────────────────────────────────────────────
# BATCH SCREENING
# ─────────────────────────────────────────────────────────────
def run_virtual_screening(
    config_path: str,
    ligands_dir: str,
    output_dir: str,
    vina_executable: str = "vina",
    affinity_cutoff: float = -6.0
) -> pd.DataFrame:
    """
    Run virtual screening of all PDBQT ligands in a directory.

    Parameters
    ----------
    config_path : str
        Vina configuration file
    ligands_dir : str
        Directory with ligand PDBQT files
    output_dir : str
        Root output directory
    vina_executable : str
        Vina binary name
    affinity_cutoff : float
        Log a note for compounds below this threshold (kcal/mol)

    Returns
    -------
    pd.DataFrame : Screening results sorted by best binding affinity
    """
    poses_dir = os.path.join(output_dir, "docked_poses")
    logs_dir  = os.path.join(output_dir, "vina_logs")
    os.makedirs(poses_dir, exist_ok=True)
    os.makedirs(logs_dir, exist_ok=True)

    ligand_files = sorted(glob.glob(os.path.join(ligands_dir, "*.pdbqt")))
    if not ligand_files:
        log.error(f"No PDBQT files found in {ligands_dir}")
        return pd.DataFrame()

    log.info(f"Starting virtual screening of {len(ligand_files)} compounds...")
    results = []

    for i, lig_path in enumerate(ligand_files, 1):
        lig_name  = Path(lig_path).stem
        out_path  = os.path.join(poses_dir, f"{lig_name}_docked.pdbqt")
        log_path  = os.path.join(logs_dir,  f"{lig_name}_vina.log")

        log.info(f"[{i}/{len(ligand_files)}] Docking {lig_name}...")
        result = run_vina(config_path, lig_path, out_path, log_path, vina_executable)

        if result["success"] and result["best_affinity"] is not None:
            if result["best_affinity"] <= affinity_cutoff:
                log.info(f"  >> HIT: {lig_name}  {result['best_affinity']:.2f} kcal/mol")
            results.append({
                "Ligand": lig_name,
                "Best_Affinity_kcal_mol": result["best_affinity"],
                "Mode2_Affinity": result["all_affinities"][1] if len(result["all_affinities"]) > 1 else None,
                "Mode3_Affinity": result["all_affinities"][2] if len(result["all_affinities"]) > 2 else None,
                "Num_Modes": len(result["all_affinities"]),
                "Docked_PDBQT": out_path,
                "Status": "Success"
            })
        else:
            results.append({
                "Ligand": lig_name, "Best_Affinity_kcal_mol": None,
                "Mode2_Affinity": None, "Mode3_Affinity": None,
                "Num_Modes": 0, "Docked_PDBQT": None, "Status": "Failed"
            })

    df = pd.DataFrame(results)
    df_success = df[df["Status"] == "Success"].sort_values("Best_Affinity_kcal_mol")
    df_failed  = df[df["Status"] == "Failed"]
    df_sorted  = pd.concat([df_success, df_failed], ignore_index=True)

    log.info(f"\nScreening complete: {len(df_success)} successful, {len(df_failed)} failed")
    return df_sorted


# ─────────────────────────────────────────────────────────────
# RESULTS & EXPORT
# ─────────────────────────────────────────────────────────────
def save_results(df: pd.DataFrame, output_dir: str, top_n: int = 20) -> None:
    """Save full results and top-N hits to CSV."""
    os.makedirs(output_dir, exist_ok=True)

    full_path = os.path.join(output_dir, "screening_results_all.csv")
    top_path  = os.path.join(output_dir, f"screening_results_top{top_n}.csv")

    df.to_csv(full_path, index=False)
    log.info(f"Full results saved to: {full_path}")

    hits = df[df["Status"] == "Success"].head(top_n)
    hits.to_csv(top_path, index=False)
    log.info(f"Top-{top_n} hits saved to: {top_path}")

    # Print summary
    if not hits.empty:
        print("\n" + "="*65)
        print(f"{'VIRTUAL SCREENING SUMMARY — TOP ' + str(top_n) + ' HITS':^65}")
        print("="*65)
        print(f"{'Rank':<6}{'Ligand':<35}{'Best Affinity (kcal/mol)':<25}")
        print("-"*65)
        for rank, (_, row) in enumerate(hits.iterrows(), 1):
            aff = f"{row['Best_Affinity_kcal_mol']:.2f}" if pd.notna(row['Best_Affinity_kcal_mol']) else "N/A"
            print(f"{rank:<6}{row['Ligand']:<35}{aff:<25}")
        print("="*65)


# ─────────────────────────────────────────────────────────────
# PHARMACOPHORE ANALYSIS (post-docking insight)
# ─────────────────────────────────────────────────────────────
def compute_binding_statistics(df: pd.DataFrame) -> dict:
    """
    Compute basic statistics on docking results.

    Returns
    -------
    dict : Summary statistics
    """
    success = df[df["Status"] == "Success"]["Best_Affinity_kcal_mol"].dropna()
    if success.empty:
        return {}
    return {
        "n_compounds_docked": len(success),
        "mean_affinity":      round(success.mean(), 2),
        "std_affinity":       round(success.std(), 2),
        "best_affinity":      round(success.min(), 2),
        "worst_affinity":     round(success.max(), 2),
        "compounds_below_6":  int((success <= -6.0).sum()),
        "compounds_below_7":  int((success <= -7.0).sum()),
        "compounds_below_8":  int((success <= -8.0).sum()),
    }


# ─────────────────────────────────────────────────────────────
# ARGUMENT PARSING & MAIN
# ─────────────────────────────────────────────────────────────
def parse_args():
    p = argparse.ArgumentParser(
        description="Automated AutoDock Vina virtual screening pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--receptor",     required=True,  help="Prepared receptor PDBQT")
    p.add_argument("--ligands_dir",  required=True,  help="Directory of ligand PDBQT files")
    p.add_argument("--config",       required=False, help="Existing Vina config (overrides --center/--size)")
    p.add_argument("--center_x",     type=float,     help="Grid box center X")
    p.add_argument("--center_y",     type=float,     help="Grid box center Y")
    p.add_argument("--center_z",     type=float,     help="Grid box center Z")
    p.add_argument("--size_x",       type=float, default=20.0, help="Grid box size X (Angstrom)")
    p.add_argument("--size_y",       type=float, default=20.0, help="Grid box size Y (Angstrom)")
    p.add_argument("--size_z",       type=float, default=20.0, help="Grid box size Z (Angstrom)")
    p.add_argument("--exhaustiveness", type=int, default=8,   help="Search exhaustiveness")
    p.add_argument("--num_modes",    type=int,   default=9,   help="Number of binding poses")
    p.add_argument("--output",       default="docking_results/",  help="Output directory")
    p.add_argument("--top_n",        type=int,   default=20,  help="Number of top hits to report")
    p.add_argument("--vina",         default="vina",           help="Vina executable path")
    p.add_argument("--cutoff",       type=float, default=-6.0, help="Affinity cutoff for hit flagging")
    return p.parse_args()


def main():
    args = parse_args()

    log.info("="*60)
    log.info("  Automated Molecular Docking Pipeline — Sana Begum")
    log.info("="*60)

    # Generate config if not provided
    if args.config:
        config_path = args.config
    else:
        if not all([args.center_x, args.center_y, args.center_z]):
            log.error("Provide --config or specify --center_x/y/z for the binding site.")
            sys.exit(1)
        config_path = os.path.join(args.output, "vina_config.txt")
        os.makedirs(args.output, exist_ok=True)
        generate_vina_config(
            receptor_path=args.receptor,
            center_x=args.center_x, center_y=args.center_y, center_z=args.center_z,
            size_x=args.size_x, size_y=args.size_y, size_z=args.size_z,
            exhaustiveness=args.exhaustiveness,
            num_modes=args.num_modes,
            config_path=config_path
        )

    # Run screening
    results_df = run_virtual_screening(
        config_path=config_path,
        ligands_dir=args.ligands_dir,
        output_dir=args.output,
        vina_executable=args.vina,
        affinity_cutoff=args.cutoff
    )

    if results_df.empty:
        log.error("No results generated. Check input files.")
        sys.exit(1)

    # Save and summarise
    save_results(results_df, args.output, top_n=args.top_n)

    stats = compute_binding_statistics(results_df)
    if stats:
        log.info("\nBinding Affinity Statistics:")
        for k, v in stats.items():
            log.info(f"  {k}: {v}")


if __name__ == "__main__":
    main()
